Add API for sync function command
kyma-incubator/hydroform pull request #132
Opened 2020-10-15 21:41 UTC by kfurgol

**Description**

Changes proposed in this pull request:

- Added API for sync function command

**Related issue(s)**
[#9403](https://github.com/kyma-project/kyma/issues/9403)

2020-10-15 21:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kyma-incubator/hydroform?pullRequest=132) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kyma-incubator/hydroform?pullRequest=132) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kyma-incubator/hydroform?pullRequest=132) it.</sub>

2020-10-15 21:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kyma-incubator/hydroform?pullRequest=132) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kyma-incubator/hydroform?pullRequest=132) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kyma-incubator/hydroform?pullRequest=132) it.</sub>

2020-10-16 13:11 UTC, kazydek requested changes

2020-10-16 13:11 UTC, kazydek commented on function/examples/sync/README.md
> +This example shows you how to synchronise serverless workspace using function api.
According to the description in [issue 9403](https://github.com/kyma-project/kyma/issues/9403), but correct me if sth has changed.

2020-10-16 13:11 UTC, kazydek commented on function/examples/sync/README.md
> +### Usage
```suggestion
## Usage
```

2020-10-16 13:11 UTC, kazydek commented on function/examples/sync/README.md
> +	--version               Show version.
Could you even these comments out? (move them a bit to the right)?
![image](https://user-images.githubusercontent.com/40655785/96262166-b681d980-0fc1-11eb-8260-3695c6f2159e.png)

2020-10-16 13:12 UTC, kazydek reviewed
Tried to change from "requesting changes" to "comments" in case I'm not the one who will double-check it, but failed :(  Let me know when you add changes and I'll double-check it.

2020-10-26 14:31 UTC, tgorgol commented on function/pkg/workspace/workspace.go
> +func synchronise(ctx context.Context, config Cfg, outputPath string, build client.Build, writerProvider WriterProvider) error {
I think that this function could use some refactoring. The whole synchronization logic is in this single function and I'm not even sure if it belongs in the `workspace` package.

2020-10-26 15:49 UTC, tgorgol approved these changes

2020-10-27 08:49 UTC, tgorgol approved these changes

2020-10-27 08:54 UTC, kazydek approved these changes
Approving as docs were moved to a separate [PR](https://github.com/kyma-incubator/hydroform/pull/134).

2020-10-27 09:35 UTC, m00g3n approved these changes

2020-10-27 09:44 UTC, merged