Move initial resource not found validation to the resource manager retry loop
kyma-incubator/hydroform pull request #216
Opened 2021-03-04 20:03 UTC by mjakobczyk

**Description**

Changes proposed in this pull request:

- remove initial `ResourceManager#getResource` call
- move resource not found logic to the retry loop
- return nil when first encounter not found error

**Related issue(s)**

Fixes #177

2021-03-08 12:32 UTC, clebs commented on parallel-install/pkg/preinstaller/resourceparser.go
> +		return nil, errors.New(fmt.Sprintf("Could not decode the resource file due to the following error: %s.", err.Error()))
Please use `errors.Wrap()` when wrapping an error into another.

2021-03-08 12:48 UTC, clebs commented on parallel-install/pkg/preinstaller/resourceparser.go
> +	_ = apiextv1.AddToScheme(sch)
Please do not ignore errors.

2021-03-09 11:11 UTC, clebs requested changes

2021-03-09 11:11 UTC, clebs commented on parallel-install/pkg/preinstaller/mocks/resourceparsermock.go
> +package mocks
For autogenerated and more flexible mocks, please check `mockery`.
You can find a full usage here:
https://github.com/kyma-project/cli/blob/bad193c82b5fa538f69335789e64bb536beb2200/internal/kube/kube.go#L15-L16

and how to use it:
https://github.com/kyma-project/cli/blob/fa37f116219247daae3487abad5499cc6fa939ec/cmd/kyma/create/system/system_test.go#L67-L68 

Writing your own mocks is a lot of unnecessary work and it adds more maintenance effort as the code evolves.
Generated mocks take all that away.

2021-03-09 11:11 UTC, clebs commented on parallel-install/pkg/preinstaller/preinstaller.go
> +			i.cfg.Log.Warn(fmt.Sprintf("Error occurred when processing resource %s of component %s : %s", resource.fileName, resource.component, err.Error()))
```suggestion
			i.cfg.Log.Warnf("Error occurred when processing resource %s of component %s : %s", resource.fileName, resource.component, err.Error())
```

2021-03-09 11:11 UTC, clebs commented on parallel-install/pkg/preinstaller/preinstaller.go
> +			i.cfg.Log.Warn(fmt.Sprintf("Resource type does not match for resource %s of component %s : got %s but expected %s", resource.fileName, resource.component, parsedResource.GroupVersionKind().Kind, r
```suggestion
			i.cfg.Log.Warnf("Resource type does not match for resource %s of component %s : got %s but expected %s", resource.fileName, resource.component, parsedResource.GroupVersionKind().Kind, resource.resourceType)
```

2021-03-09 11:11 UTC, clebs commented on parallel-install/pkg/preinstaller/preinstaller.go
>  		i.cfg.Log.Info(fmt.Sprintf("Processing %s file: %s of component: %s", resource.resourceType, resource.fileName, resource.component))
```suggestion
		i.cfg.Log.Infof("Processing %s file: %s of component: %s", resource.resourceType, resource.fileName, resource.component)
```

2021-03-09 11:11 UTC, clebs commented on parallel-install/pkg/preinstaller/preinstaller.go
>  			i.cfg.Log.Warn(fmt.Sprintf("Error occurred when processing file %s of component %s : %s", resource.fileName, resource.component, err.Error()))
```suggestion
			i.cfg.Log.Warnf("Error occurred when processing file %s of component %s : %s", resource.fileName, resource.component, err.Error())
```

2021-03-09 11:11 UTC, clebs commented on parallel-install/pkg/preinstaller/resourceparser.go
> +func NewGenericResourceParser() *GenericResourceParser {
If a constructor is not doing anything on the struct, it is not needed. One can just instantiate the struct:
`grp := &preinstaller.GenericResourceParser{}`

2021-03-11 14:30 UTC, Tomasz-Smelcerz-SAP commented on parallel-install/pkg/preinstaller/preinstaller.go
> +		parsedResource, err := i.parser.ParseUnstructuredResourceFrom(file.path)
```suggestion
		parsedResource, err := i.parser.ParseFile(file.path)
```

2021-03-11 14:48 UTC, Tomasz-Smelcerz-SAP commented on parallel-install/pkg/preinstaller/resourcemanager.go
>  		return err
The code would be a bit more readable if a `nil` is returned here.

2021-03-11 14:55 UTC, Tomasz-Smelcerz-SAP approved these changes

2021-03-11 16:37 UTC, clebs approved these changes

2021-03-12 11:22 UTC, merged